export enum MotivoBaixa {
  LEILAO = 'LEILAO',
  DOACAO = 'DOACAO',
  INSERVIVEL = 'INSERVIVEL',
  EXTRAVIO = 'EXTRAVIO',
  DESCARTE = 'DESCARTE',
  TRANSFERENCIA_DEFINITIVA = 'TRANSFERENCIA_DEFINITIVA',
  OUTRO = 'OUTRO',
}
