export enum StatusMovimentacao {
  AGUARDANDO_CONFIRMACAO_ENTREGA = 'AGUARDANDO_CONFIRMACAO_ENTREGA',
  AGUARDANDO_CONFIRMACAO_RECEBIMENTO = 'AGUARDANDO_CONFIRMACAO_RECEBIMENTO',
  AGUARDANDO_APROVACAO_PATRIMONIO = 'AGUARDANDO_APROVACAO_PATRIMONIO',
  APROVADA = 'APROVADA',
  REJEITADA = 'REJEITADA',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
}
